### ISSUE TITLE
Legal license mix up

### ISSUE THREAD

**Issue by aggsol** [Mervill/Unity3D-NLua#10]
Before I use `Unity3D-NLua` I have to clear the licensing first. Lua itsel, KopiLua and NLua are licensed with the `MIT license` but you added also the `Boost license` to your project? Is there any reasoning behind it? Is the mixup of those licenses possible?

**Comment by Mervill** [comment]
The boost and MIT licenses differ only in attribution. The MIT insists on attribution at all times, while the  boost licence provides an exception:

```
unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.
```

So if you redistribute the source files, attribution is required, but if you include the code as part of a binary (ie, in a compiled game) attribution is not necessary.

Your safest bet would be to attribute NLua only, not this project, in released copies of your software.

**Comment by Mervill** [comment]
If you have more questions, feel free to reopen this issue or post a new one.
